import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowRight, Clock3, Gavel, Heart, MapPin, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function AuctionDetail() {
  const { isAuthenticated } = useAuth();
  return <main dir="rtl" className="min-h-screen bg-[#f7f6f1] text-[#143039]"><header className="market-container flex h-20 items-center justify-between"><Link href="/" className="font-serif text-2xl font-semibold">مِزَاد</Link><Link href="/" className="flex items-center gap-2 text-sm font-bold"><ArrowRight size={17} /> الرجوع للمزادات</Link></header><section className="market-container grid gap-8 pb-16 pt-6 lg:grid-cols-[1.15fr_.85fr]"><div className="relative min-h-[31rem] overflow-hidden rounded-[2rem] bg-[radial-gradient(circle_at_70%_22%,rgba(255,255,255,.38),transparent_24%),linear-gradient(140deg,#13242c,#526d7b,#e7d1a1)]"><span className="absolute left-8 top-7 font-serif text-[12rem] leading-none text-white/90">⌁</span><button className="absolute right-6 top-6 grid h-11 w-11 place-items-center rounded-full bg-white/90" aria-label="حفظ المزاد"><Heart size={19} /></button><div className="absolute bottom-6 right-6 rounded-full bg-[#12313a]/75 px-4 py-2 text-xs font-bold text-white backdrop-blur">معاينة الوسائط الخاصة عند ربط خدمة التخزين</div></div><aside className="rounded-[2rem] bg-white p-7 shadow-[0_15px_50px_rgba(20,48,57,.08)] md:p-9"><p className="text-xs font-bold text-[#d96d46]">ساعات ومجوهرات · مزاد حي</p><h1 className="mt-3 font-serif text-4xl leading-tight">ساعة كرونوغراف كلاسيكية</h1><p className="mt-4 flex items-center gap-2 text-sm text-[#6d7e82]"><MapPin size={16} />الرياض · المملكة العربية السعودية</p><div className="mt-8 rounded-2xl bg-[#edf0e8] p-5"><div className="flex flex-col gap-2 text-sm sm:flex-row sm:items-center sm:justify-between"><span className="text-[#64777b]">المزايدة الحالية</span><strong className="font-serif text-2xl sm:text-3xl">12,800 ر.س</strong></div><div className="mt-5 flex items-center gap-2 border-t border-[#143039]/10 pt-4 text-sm font-bold text-[#bf5a36]"><Clock3 size={17} /> ينتهي خلال 01:42:18</div></div><div className="mt-6 flex flex-col gap-2 sm:flex-row"><input aria-label="قيمة المزايدة" placeholder="أدخل مزايدتك" className="min-w-0 flex-1 rounded-xl border border-[#143039]/15 px-4 py-3 text-sm outline-none focus:border-[#d96d46]" /><button onClick={isAuthenticated ? undefined : startLogin} className="flex items-center justify-center gap-2 rounded-xl bg-[#12313a] px-4 py-3 text-sm font-bold text-white"><Gavel size={16} />زايد الآن</button></div><div className="mt-6 flex gap-2 rounded-xl border border-[#143039]/10 p-4 text-xs leading-5 text-[#61757a]"><ShieldCheck className="mt-0.5 shrink-0 text-[#5e7e69]" size={18} />تحتاج المزايدة الفعلية حساباً موثقاً وسياق بلد مطابقاً.</div></aside></section></main>;
}
